require: rubocop-rails

AllCops:
  NewCops: enable

Layout/LineLength:
  Max: 128

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false
